### ISSUE TITLE
Final checklist

### ISSUE THREAD

**Issue by tharshita** [danielwys/FoodSloth#16]
- [x] enable customer to add rest promo to an order
- [x] Customer view existing orders
- [x] add more data to sample sql 
- [x] account for discounted prices in summary and past items
- [x] update changes to completed orders in report
- [x] update changes to promos in report
- [x] let manager create customer promos
- [x] do final check if everything links (deadline: 5 pm)

- [x] finish summary for managers (riders summary)
- [x] customer review & rating for completed orders
- [x] restaurant address
- [x] add address field when creating restaurant
- [x] finalise an order
- [x] customer view past completed orders
- [x] customer view past items
- [x] customer view reward points
- [x] customer change credit card number
- [x] change ER bcnf explanation for orderitems in doc
- [x] finish summary for restaurants promo
